FROM python:3.13-slim
LABEL author="Pep Catalina i Guillem Torres"
LABEL title="Api Digitalitzacio"
LABEL version="1.0"

# Establir directori de treball
WORKDIR /app

# Copiar e instal·lar dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && pip install net-tools

# Copiar todo el codi de la API
COPY . .

# Exposar el por 5000 de FLASK (5000 por defecto)
EXPOSE 5000

# Iniciar el servidor Flask
CMD ["python", "app.py"]
