
version: '3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: taller
    networks:
      - taller_net
  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - taller_net
  web:
    image: nginx:alpine
    volumes:
      - ./web:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - taller_net

networks:
  taller_net:
