FROM alpine:latest

LABEL author="Pep Catalina i Guillem Torres"
LABEL title="NGINX Digitalitzacio"
LABEL version="1.0"

RUN apk update && apk add nginx bind bind-tools 


COPY nginx.conf /etc/nginx/nginx.conf
COPY named.* /etc/bind/
COPY db.* /etc/bind/
COPY centreMedic /var/www/centremedic

VOLUME /var/www
VOLUME /etc/bind

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]


