FROM alpine:latest

LABEL author="Pep Catalina i Guillem Torres"
LABEL title="NGINX Digitalitzacio"
LABEL version="1.0"

# Instal·lar NGINX i altres utilitats
RUN apk update && apk add --no-cache nginx bind bind-tools iputils net-tools

# Copiar fitxers de configuració
COPY nginx.conf /etc/nginx/nginx.conf
COPY named.* /etc/bind/
COPY db.* /etc/bind/
COPY centreMedic /var/www/centreMedic

# Creaciode volums
VOLUME /var/www
VOLUME /etc/bind

# Exposar ports HTTP i HTTPS
EXPOSE 80 443

# Iniciar el servidor NGINX
CMD ["nginx", "-g", "daemon off;"]