FROM mariadb:latest

LABEL author="Pep Catalina i Guillem Torres"
LABEL title="MariaDB Digitalitzacio"
LABEL version="1.0"

ENV MYSQL_ROOT_PASSWORD=Educem00.

COPY init.sql /docker-entrypoint-initdb.d/init.sql
COPY backup.sh /Backup_MySQL/backup.sh
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /Backup_MySQL/backup.sh /entrypoint.sh

EXPOSE 3306

ENTRYPOINT ["/entrypoint.sh"]
